name : Terraform Backend Deployment

on:
    push:
        paths:
            - 'terraform-backend/**'
    pull_request:
        paths:
            - 'terraform-backend/**'
jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name : Login to Azure using OIDC
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            # - name: Deploy Bicep template
            #   uses: azure/powershell@v2
            #   with:
            #     inlineScript: ./scripts/run_azps_cmdlets.ps1
            #     azPSVersion: "latest"